version: '2'
services:
 ovpn-data:
   image: busybox
   volumes:
    - .:/etc/openvpn
   container_name: ovpn-data

 genconfig:
   image: kylemanna/openvpn
   volumes_from:
    - container:ovpn-data
   command: ovpn_genconfig -u udp://${OVPN_HOSTNAME}

 initpki:
   image: kylemanna/openvpn
   volumes_from:
    - container:ovpn-data
   command: ovpn_initpki

 openvpn-server:
   image: kylemanna/openvpn
   volumes_from:
    - ovpn-data
   ports:
    - "1194:1194/udp"
   cap_add:
    - NET_ADMIN
   restart: "always"
   network_mode: "host"
   environment:
    - OVPN_NATDEVICE=${OVPN_NATDEVICE}
   container_name: openvpn-server

 genclient:
   image: kylemanna/openvpn
   volumes_from:
    - container:ovpn-data