ovpn-data:
  image: hypriot/armhf-busybox
  volumes:
  - /etc/openvpn

genconfig:
  image: evolvedm/openvpn-rpi
  volumes_from:
  - ovpn-data
  command: ovpn_genconfig -u udp://${OVPN_HOSTNAME}

initpki:
  image: evolvedm/openvpn-rpi
  volumes_from:
  - ovpn-data
  command: ovpn_initpki

openvpn-server:
  image: evolvedm/openvpn-rpi
  volumes_from:
  - ovpn-data
  ports:
  - "1194:1194/udp"
  cap_add:
  - NET_ADMIN
  restart: always
  net: host
  environment:
    - OVPN_NATDEVICE=${OVPN_NATDEVICE}
  container_name: openvpn-server

genclient:
  image: evolvedm/openvpn-rpi
  volumes_from:
  - ovpn-data