version: '2'

volumes: 
    ovpn-data:

services:
  genconfig:
    image: evolvedm/openvpn-rpi
    command: ovpn_genconfig -u udp://${OVPN_HOSTNAME}
    volumes:
      - ovpn-data:/etc/openvpn

  initpki:
    image: evolvedm/openvpn-rpi
    command: ovpn_initpki
    volumes:
      - ovpn-data:/etc/openvpn

  openvpn-server:
    image: evolvedm/openvpn-rpi
    container_name: openvpn-server
    command: ovpn_initpki
    volumes:
      - ovpn-data:/etc/openvpn
    network_mode: "host"
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    restart: "always"

  genclient:
    image: evolvedm/openvpn-rpi
    volumes:
      - ovpn-data:/etc/openvpn
